title: "GenAI Games"
email: "maarten.bassier@kuleuven.be"
description: "A playful, high-energy research event where PhD researchers compete in mixed teams to solve short challenges using generative AI."
baseurl: ""
url: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation
nav:
  - title: Home
    url: /
  - title: Subscription
    url: /subscription/
  - title: Tasks
    url: /tasks/
  - title: Leaderboard
    url: /leaderboard/